package com.storehub.entity;

/**
 * Classification of a Product's barcode value, auto-detected server-side
 * from its format (Barcode Management spec sections 5/10/11) — never chosen
 * by the user, so the Item Master form stays a single plain "Barcode" field.
 * Only {@link #EAN13} gets checksum validation; every other type is stored
 * as an opaque scannable string.
 */
public enum BarcodeType {
    EAN13,
    EAN8,
    UPC,
    /** Internally generated by {@code BarcodeGeneratorService} (INT-000001 format) — never an official retail barcode. */
    INTERNAL,
    OTHER
}
